### ISSUE TITLE
Usage with Puppet Enterprise

### ISSUE THREAD

**Issue by rfults** [theforeman/puppet-foreman_scap_client#29]
I tried configuring this in Puppet Enterprise console and I am seeing some strange issues.  I am seeing the variable names written directly to the  cron file and the client config, e.g.:

# DO NOT EDIT THIS FILE MANUALLY
# IT IS MANAGED BY PUPPET

# foreman_scap_client cron job
# Runs foreman_scap_client id
minute hour monthday month weekday root /usr/bin/foreman_scap_client id > /dev/null

I've tried defining the array in several different ways (removing and escaping quotes, removing var names, etc.) and just can't seem to get this working.

**Comment by ares** [comment]
This module is meant to be used with [foreman_openscap](https://github.com/theforeman/foreman_openscap) plugin, the ENC output generated by [Foreman](https://theforeman.org/) for it is based on configured policies for a given puppet agent. It also needs smart_proxy_openscap plugin to properly download content files. If you want to experiment, here's an example of ENC output that Foreman generates.

``` yaml
classes:
  foreman_scap_client:
    policies:
    - id: 5
      profile_id: xccdf_org.ssgproject.content_profile_stig-openstack
      content_path: "/var/lib/openscap/content/3e1654fd14a5352d65294db555710bfda5cad1a942209e2d787ea7940035616e.xml"
      download_path: "/compliance/policies/5/content"
      minute: "*"
      hour: '5'
      monthday: "*"
      month: "*"
      weekday: "*"
    port: 8443
    server: foreman.example.tst
```
